#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname $(readlink -f "${BASH_SOURCE[0]}") )" &> /dev/null && pwd )"

pushd "$SCRIPT_DIR" > /dev/null

if [ ! -d venv ]; then
    python3 -m venv venv
    . venv/bin/activate
    pip install -r requirements.txt
fi

. venv/bin/activate

popd > /dev/null

"$SCRIPT_DIR/peepo.py" "$@"
